### ISSUE TITLE
When a user send a message I want to reply to the message and send a DM

### ISSUE THREAD

**Issue by nmolenaar** [Katrix/AckCord#22]
Hey guys, 

Thank you for the library its been working greet so far.
Just wondering how would some one reply to a user message in a channel by DM? 

`req.user.getDMChannel(req.cache) match {
      case Some(channel) => client.requestsHelper.runMany(
        req.textChannel.sendMessage(s"Ill DM you @${req.user.username}"),
        channel.sendMessage("Sup")
      )(req.cache)`

This works great if the user already has an DM window open with the bot but creating a new window for a DM is a tricky situation I cannot seem to solve.

**Comment by Katrix** [comment]
`req.user.createDMChannel`. Next time ask in the Discord first before opening an issue. Also, the cache is intended to be passed around implicitly.
