### ISSUE TITLE
Member add/update events not being triggered

### ISSUE THREAD

**Issue by AlexITC** [Katrix/AckCord#30]
I have an app that expects the `APIMessage.GuildMemberAdd`/`APIMessage.GuildMemberUpdate` events,  but since I updated to `0.17.0-M1`, I haven't been getting them, I tried `0.17.0-M2` without luck.

**Comment by Katrix** [comment]
Are you setting the right intents? The guild members events a privileged and as such AckCord won't set that intent by default.

**Comment by AlexITC** [comment]
I have no idea what are you referring to, but, I'm using the same code I used with `0.16.1`, where these events were being captured. There are no changes on the discord role either.

**Comment by Katrix** [comment]
Discord released intents, which is a way to specify what events a bot will receive, a few months ago now. These can be set in AckCord in the `ClientSettings` object. You likely want `GatewayIntents.AllNonPrivileged++ GatewayIntents.GuildMembers`.

Before you start the bot again, you'll have to enable the guild members intent in the bot settings, same place where you find the bot token.

![image](https://user-images.githubusercontent.com/11007080/89713631-7a5e4700-d988-11ea-96da-2d3529596985.png)

**Comment by AlexITC** [comment]
Ok, I wasn't aware of those changes, but I can confirm that reverting back to `0.16.1` has fixed the issue.

I analyzed a bit, and the default intends on the previous version used to include the member related events, while the current version does not (`AllNonPrivileged`).

I confirm that using the right intents gets the bot working again, thanks!

In any case
