### ISSUE TITLE
How can I use this library for my project?

### ISSUE THREAD

**Issue by aperture147** [Katrix/AckCord#5]
I want to use this for my bot, but I can't fetch it from maven server. I also don't want to make a JAR file from this. Can you gimme some help?

**Comment by Katrix** [comment]
What do you mean that you can't fetch it from maven? What did you try, and what error did you get?

**Comment by llamositopia** [comment]
Maybe needs to add the Sonatype repo resolver?

**Comment by Katrix** [comment]
lavaplayer can be found on JCenter. Currently it seems that jcenter is specified for the wrong dependency. I can move it to the lavaplayer module and hope that works. In the meantime just add `resolvers += JCenterRepository` to your build file.

**Comment by Katrix** [comment]
Fixed in master. For stuff before 0.11, for the version it's `0.10.0` not `0.10` and you also need the JCenter resolver.
