### ISSUE TITLE
Ping command in example bot shouldn't take any arguments

### ISSUE THREAD

**Issue by dienzo76** [Katrix/AckCord#6]
I tried the example bot, successfully connected it to my discord server but none of the implemented command work (!ping etc), the only thing that work is when i private message the bot, it reply back to me.
Any ideas of what could be the problem ?
Thanks in advance.

**Comment by Katrix** [comment]
The default behavior for commands is to require a mention. Did you do that? `@MyBot !ping`? This is done to help combat the problem of hogging common prefixes for commands.

**Comment by dienzo76** [comment]
I actually did try that and when i do it the bot reply with "No more arguments left" and if i put an arg like this "@TestBot !ping hello" it will reply "For input string: "hello" i don't understand why it doesn't reply with "Received ping command with arg" since the code is this ``{
          override def handle(msg: Message, args: Int, remaining: List[String])(implicit c: CacheSnapshot[Id]): Unit =
            println(s"Received ping command with arg $args")
        }``
Sorry if it's a silly question i'm a beginner in programming.
Thanks in advance.

**Comment by Katrix** [comment]
Welp, I screwed up the example bot commands. Sorry about that. What's happening here is that the second argument is the "parsed" argument. Here it expects a number, but you never give it one. If you change the `args: Int` to `args: NotUsed` it should work fine. Remember to also change `CommandHandler[Int]` to `CommandHandler[NotUsed]`. Alternatively, you can provide a number when you invoke the command like so. `@MyBot !ping 5`.

Lastly, while you can follow the example bot found on master, and that one might contain fixes, it will probably also contain other future changes. Preferably 0.11 would already be out, but my connection was crap last time I tried to publish, and I'm on vacation atm. If you want code that is guaranteed to work with 0.10, check out the repository at that point instead. https://github.com/Katrix/AckCord/tree/7db2e5c5499a4bf7e97eaaad3725ee768486f5da

**Comment by Katrix** [comment]
Should be fixed in master

**Comment by dienzo76** [comment]
Sorry i totally forgot about this, thanks I will check it out again 😄
