### ISSUE TITLE
HelpCmd.Args Parser doesn't agree with cases in the HelpCmd receive

### ISSUE THREAD

**Issue by Bathtor** [Katrix/AckCord#9]
After digging into the code for an hour or so to see why the HelpCommand example doesn't reply, I figured out that the [parser](https://github.com/Katrix/AckCord/blob/7db2e5c5499a4bf7e97eaaad3725ee768486f5da/ackCordCommandsCore/src/main/scala/net/katsstuff/ackcord/commands/HelpCmd.scala#L150) returns either an `HelpCmd.Args` instance, or replies with an error message. But the actor's [receive](https://github.com/Katrix/AckCord/blob/7db2e5c5499a4bf7e97eaaad3725ee768486f5da/ackCordCommandsCore/src/main/scala/net/katsstuff/ackcord/commands/HelpCmd.scala#L56) expects an `Option[HelpCmd.Args]` instead (and silently ignores unmatched messages).

**Comment by Katrix** [comment]
Yep, known and fixed in master
